### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: relocated/acf/ACFUtil$ApplyModifierToNumber

### ISSUE THREAD

**Issue by yannicklamprecht** [aikar/commands#205]
I got the exception that the class couldn't be found. The shading process is done like descripted in the maven subsection. https://github.com/aikar/commands/wiki/Maven-Setup

`Caused by: java.lang.NoClassDefFoundError: relocated/acf/ACFUtil$ApplyModifierToNumber
        at relocated.acf.ACFUtil.parseNumber(ACFUtil.java:468) ~[?:?]
        at relocated.acf.CommandContexts.parseAndValidateNumber(CommandContexts.java:254) ~[?:?]
        at relocated.acf.CommandContexts.lambda$new$4(CommandContexts.java:72) ~[?:?]
        at relocated.acf.RegisteredCommand.resolveContexts(RegisteredCommand.java:282) ~[?:?]
        at relocated.acf.RegisteredCommand.resolveContexts(RegisteredCommand.java:202) ~[?:?]
        at relocated.acf.RegisteredCommand.invoke(RegisteredCommand.java:147) ~[?:?]
        at relocated.acf.BaseCommand.executeCommand(BaseCommand.java:576) ~[?:?]
        at relocated.acf.BaseCommand.execute(BaseCommand.java:512) ~[?:?]
        at relocated.acf.RootCommand.execute(RootCommand.java:99) ~[?:?]
        at relocated.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-564]
        ... 14 more
`
original relocation package is replaced by relocated.

Is the usage of the command completion range as intended? Do I need to use the wrapper class Integer instead to get it working probably or is there a bug with the shading process?
Or could it be that the spigot/Bukkit version do not work with paper and the paper version should be used instead?

`
@Subcommand("expand")
@CommandPermission("some.permission")
@CommandCompletion("@range:1-10")
public void expandRegion(Player player, int amount){}
`

**Comment by aikar** [comment]
can you paste your pom?

**Comment by yannicklamprecht** [comment]
https://gist.github.com/yannicklamprecht/58cb804bfbdbb115f1d7785bef3aad3a

**Comment by yannicklamprecht** [comment]
Seems like the bug doesn't happen anymore strange. Will observe it.
