### ISSUE TITLE
java.lang.NoSuchMethodError on PluginDisableEvent

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#23]
```
[16:50:46] [Server thread/ERROR]: Could not pass event PluginDisableEvent to AdvancedKitsReloaded v1.0.4-pre
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:355) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.command.CommandMap.getKnownCommands()Ljava/util/Map;
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager.lambda$unregisterCommand$0(BukkitCommandManager.java:128) ~[?:?]
	at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_121]
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager.unregisterCommand(BukkitCommandManager.java:125) ~[?:?]
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager.unregisterCommands(BukkitCommandManager.java:141) ~[?:?]
	at hu.tryharddevs.advancedkits.utils.afc.BukkitCommandManager$1.onPluginDisable(BukkitCommandManager.java:69) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-e04a179]
	... 10 more
```
* Group: co.aikar
* Artifact: acf-core
* Version: 0.4.0-SNAPSHOT

**Comment by simpleauthority** [comment]
Hi, what version of Bukkit are you running?

**Comment by aikar** [comment]
This should now be fixed, please recompile.
