### ISSUE TITLE
IllegalAccessException in BukkitCommandManager

### ISSUE THREAD

**Issue by egg82** [aikar/commands#234]
Got someone who gave me a stacktrace for their server using my plugin (which uses ACF):

```
[15:11:23 INFO]: [AntiVPN] {m.e.a.e.PlayerLoginCheckHandler} [Anti-VPN] RandomUser passed VPN check.
> [15:11:23 INFO]: [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
> [15:11:23 INFO]: [ACF] java.lang.IllegalAccessException: Class co.aikar.commands.BukkitCommandManager can not access a member of class net.minecraft.server.v1_8_R3.EntityPlayer with modifiers "private"
> [15:11:23 INFO]: [ACF] at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
> [15:11:23 INFO]: [ACF] at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
> [15:11:23 INFO]: [ACF] at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
> [15:11:23 INFO]: [ACF] at java.lang.reflect.Field.get(Field.java:390)
> [15:11:23 INFO]: [ACF] at co.aikar.commands.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:314)
> [15:11:23 INFO]: [ACF] at co.aikar.commands.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:54)
> [15:11:23 INFO]: [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15:11:23 INFO]: [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [15:11:23 INFO]: [ACF] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15:11:23 INFO]: [ACF] at java.lang.reflect.Method.invoke(Method.java:498)
> [15:11:23 INFO]: [ACF] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
> [15:11:23 INFO]: [ACF] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [15:11:23 INFO]: [ACF] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
> [15:11:23 INFO]: [ACF] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:282)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:142)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:115)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:53)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:222)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:168)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:745)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629)
> [15:11:23 INFO]: [ACF] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537)
> [15:11:23 INFO]: [ACF] at java.lang.Thread.run(Thread.java:748)
```

**Comment by chickeneer** [comment]
The fix is deployed. Thanks for the report.
