### ISSUE TITLE
PaperCommandManager causing Timings NPE

### ISSUE THREAD

**Issue by knightzmc** [aikar/commands#264]
This should possibly be in minecraft-timings, but the PaperCommandManager seems to be causing an NPE on initialisation. This seems to relate to `CustomTimingsHandler` being used, even though the class `co.aikar.timings.Timing` is definitely present at runtime. 

Running: Paper 1.15.2, latest build
ACF-Paper 0.5.0 latest build,

```
java.lang.NullPointerException: null
        at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:79) ~[patched_1.15.2.jar:git-Paper-245]
        at me.bristermitten.powertools.acf.commands.lib.timings.SpigotTiming.<init>(SpigotTiming.java:11) ~[?:?]
        at me.bristermitten.powertools.acf.commands.lib.timings.TimingType$1.newTiming(TimingType.java:11) ~[?:?]
        at me.bristermitten.powertools.acf.commands.lib.timings.TimingManager.of(TimingManager.java:72) ~[?:?]
        at me.bristermitten.powertools.acf.commands.lib.timings.TimingManager.of(TimingManager.java:38) ~[?:?]
        at me.bristermitten.powertools.acf.commands.BukkitCommandManager.<init>(BukkitCommandManager.java:97) ~[?:?]
        at me.bristermitten.powertools.acf.commands.PaperCommandManager.<init>(PaperCommandManager.java:33) ~[?:?]
        at me.bristermitten.powertools.PowerTools.setupCommands(PowerTools.kt:40) ~[?:?]
        at me.bristermitten.powertools.PowerTools.onEnable(PowerTools.kt:20) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-245]
```

Apologies if this belongs somewhere else

**Comment by darbyjack** [comment]
Can you attach your build.gradle or pom please?

**Comment by knightzmc** [comment]
```gradle
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.60'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.3.60'

    id 'com.github.johnrengelman.shadow' version '4.0.4'
}

group 'me.bristermitten'
version '1.0'

sourceCompatibility = 1.8

repositories {
    jcenter()
    mavenCentral()

    maven { url "https://papermc.io/repo/repository/maven-public/" }
    maven { url "https://hub.spigotmc.org/nexus/content/groups/public/" }
    maven { url "https://repo.aikar.co/content/groups/aikar/" }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0'
    implementation 'com.charleskorn.kaml:kaml:0.15.0'

    compileOnly 'com.destroystokyo.paper:paper-api:1.15.2-R0.1-SNAPSHOT'
    implementation "co.aikar:acf-paper:0.5.0-SNAPSHOT"

    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile 'com.github.knightzmc:MockBukkit:4afe7bda8bfad66811634e6fae544dcdb52f32a3'
}

shadowJar {
    relocate 'co.aikar', 'me.bristermitten.powertools.acf'
    minimize()
}

compileJava {
    options.compilerArgs += ["-parameters"]
    options.fork = true
    options.forkOptions.executable = 'javac'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
    kotlinOptions.javaParameters = true
}

compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

```

**Comment by knightzmc** [comment]
I believe I've just noticed the problem in my relocation. Let me check...

**Comment by knightzmc** [comment]
Yeah, I was relocating `co.aikar` instead of `co.aikar.commands`. This is now fixed, thanks for the help!

**Comment by darbyjack** [comment]
> Yeah, I was relocating `co.aikar` instead of `co.aikar.commands`. This is now fixed, thanks for the help!

Keep in mind with the latest update you also have to relocate locales. https://github.com/aikar/commands/wiki/Gradle-Setup
