### ISSUE TITLE
NullPointerException when typing command with number above integer limit

### ISSUE THREAD

**Issue by Archy-X** [aikar/commands#288]
NullPointerException occurs when typing a command with a number above integer limit with the Help API enabled.

It occurs when typing in a command that doesn't exist and is supposed to bring up the help page

`[08:12:55 INFO]: I'm sorry, but there was an error performing this command.
[08:12:55 ERROR]: [AureliumSkills] [ACF] Exception in command: skills 2147483648
[08:12:55 ERROR]: [AureliumSkills] [ACF] java.lang.NullPointerException
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.CommandContexts.lambda$new$20(CommandContexts.java:232)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.RegisteredCommand.resolveContexts(RegisteredCommand.java:298)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.RegisteredCommand.resolveContexts(RegisteredCommand.java:217)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.RegisteredCommand.invoke(RegisteredCommand.java:151)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.BaseCommand.execute(BaseCommand.java:513)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.RootCommand.execute(RootCommand.java:99)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at com.archyx.aureliumskills.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:82)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[08:12:55 ERROR]: [AureliumSkills] [ACF] at java.lang.Thread.run(Thread.java:748)`

**Comment by jmanpenilla** [comment]
https://paste.gg/p/anonymous/286e2ec87e0f44c0a4d1890d6e285c3d lol, can confirm
