### ISSUE TITLE
NoClassDefFoundError in apache commons

### ISSUE THREAD

**Issue by BlackBaroness** [aikar/commands#329]
```
[00:49:38 WARN]: Unhandled exception when tab completing
java.util.concurrent.ExecutionException: org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'auth unregister Bl' in ru.baronessdev.paid.auth.lib.acf.core.BukkitRootCommand(auth)
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.get(Waitable.java:42) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter.complete(ConsoleCommandCompleter.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:3962) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:3875) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:585) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer$2.run(DedicatedServer.java:77) ~[patched_1.12.2.jar:git-Paper-1618]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'auth unregister Bl' in ru.baronessdev.paid.auth.lib.acf.core.BukkitRootCommand(auth)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:237) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:183) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:68) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:65) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:861) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: ru/baronessdev/paid/auth/lib/apache/commons/lang/Validate
        at ru.baronessdev.paid.auth.lib.acf.core.BukkitCommandCompletions.lambda$new$8(BukkitCommandCompletions.java:74) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.CommandCompletions.getCompletionValues(CommandCompletions.java:259) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.CommandCompletions.of(CommandCompletions.java:205) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BaseCommand.completeCommand(BaseCommand.java:701) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BaseCommand.tabComplete(BaseCommand.java:642) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.lambda$getTabCompletions$1(RootCommand.java:125) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.getTabCompletions(RootCommand.java:123) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.getTabCompletions(RootCommand.java:118) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.getTabCompletions(RootCommand.java:114) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BukkitRootCommand.tabComplete(BukkitRootCommand.java:75) ~[?:?]
        at org.bukkit.command.Command.tabComplete(Command.java:90) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:183) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:68) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:65) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:861) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.ClassNotFoundException: ru.baronessdev.paid.auth.lib.apache.commons.lang.Validate
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BukkitCommandCompletions.lambda$new$8(BukkitCommandCompletions.java:74) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.CommandCompletions.getCompletionValues(CommandCompletions.java:259) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.CommandCompletions.of(CommandCompletions.java:205) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BaseCommand.completeCommand(BaseCommand.java:701) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BaseCommand.tabComplete(BaseCommand.java:642) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.lambda$getTabCompletions$1(RootCommand.java:125) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.getTabCompletions(RootCommand.java:123) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.getTabCompletions(RootCommand.java:118) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.RootCommand.getTabCompletions(RootCommand.java:114) ~[?:?]
        at ru.baronessdev.paid.auth.lib.acf.core.BukkitRootCommand.tabComplete(BukkitRootCommand.java:75) ~[?:?]
        at org.bukkit.command.Command.tabComplete(Command.java:90) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:183) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:68) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:65) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:861) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```
ver 0.5.0-SNAPSHOT

**Comment by BlackBaroness** [comment]
That was my mistake, i relocated Apache Commons
