### ISSUE TITLE
Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP

### ISSUE THREAD

**Issue by kyngs** [aikar/commands#378]
The moment I create a new PaperCommandManager (Which applies to BukkitCommandManager as well), my log gets spammed by this exception about 20 times. Each time with a different stack trace
First exception:
```
org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP
[20:35:15 WARN]: 	at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:51)
[20:35:15 WARN]: 	at <REDACTED>//<REDACTED>.acf.commands.lib.timings.SpigotTiming.<init>(SpigotTiming.java:11)
[20:35:15 WARN]: 	at <REDACTED>//<REDACTED>.acf.commands.lib.timings.TimingType$1.newTiming(TimingType.java:11)
[20:35:15 WARN]: 	at <REDACTED>//<REDACTED>.acf.commands.lib.timings.TimingManager.of(TimingManager.java:72)
[20:35:15 WARN]: 	at <REDACTED>//<REDACTED>.acf.commands.lib.timings.TimingManager.of(TimingManager.java:38)
[20:35:15 WARN]: 	at <REDACTED>//<REDACTED>.acf.commands.BukkitCommandManager.<init>(BukkitCommandManager.java:101)
[20:35:15 WARN]: 	at <REDACTED>//<REDACTED>.acf.commands.PaperCommandManager.<init>(PaperCommandManager.java:35)
```

EDIT: It appears that this nag is not surpassable, which makes it a kind of urgent matter.

**Comment by RoinujNosde** [comment]
Check your shader patterns. 
You're probably relocating "co.aikar" instead of "co.aikar.acf".

**Comment by kyngs** [comment]
> Check your shader patterns. You're probably relocating "co.aikar" instead of "co.aikar.acf".

Ouch, that was it. Will be more careful next time, thanks.
