### ISSUE TITLE
NoSuchMethodError for threadedregions.scheduler.AsyncScheduler on 1.19.4

### ISSUE THREAD

**Issue by Archy-X** [aikar/commands#395]
I'm getting multiple reports of a NoSuchMethodError on 1.19.4 servers on startup. ACF seems to try to initialize Folia related schedulers on a non-Folia server that doesn't have the new Paper threadedregions scheduler code.
```
[05:59:32] [Server thread/ERROR]: Error occurred while enabling AureliumSkills vBeta 1.3.21 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Bukkit.getAsyncScheduler()'
	at com.archyx.aureliumskills.acf.ACFFoliaScheduler.createLocaleTask(ACFFoliaScheduler.java:51) ~[AureliumSkills-Beta1.3.21.jar:?]
	at com.archyx.aureliumskills.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:132) ~[AureliumSkills-Beta1.3.21.jar:?]
	at com.archyx.aureliumskills.acf.PaperCommandManager.<init>(PaperCommandManager.java:34) ~[AureliumSkills-Beta1.3.21.jar:?]
	at com.archyx.aureliumskills.AureliumSkills.onEnable(AureliumSkills.java:260) ~[AureliumSkills-Beta1.3.21.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Archy-X** [comment]
I see #394 now.
