### ISSUE TITLE
Error on Server Shutdown

### ISSUE THREAD

**Issue by Komeek** [aikar/commands#397]
I get this weird error when the server shuts down.

I know that there is an issue that occurs when unregistering a command but I'm unsure which and why.
```
[20:25:04 ERROR]: Could not pass event PluginDisableEvent to Metro v1.0
org.bukkit.event.EventException: An exception was thrown while invoking a listener.
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$3(CarbonPluginLoader.java:191) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:341) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:434) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:427) ~[server.jar:git-Carbon-0b81a54]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:425) ~[server.jar:git-Carbon-0b81a54]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:521) ~[server.jar:git-Carbon-0b81a54]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:710) ~[server.jar:git-Carbon-0b81a54]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:134) ~[server.jar:git-Carbon-0b81a54]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.NullPointerException
        at xyz.refinedev.core.acf.BukkitCommandManager.unregisterCommand(BukkitCommandManager.java:279) ~[?:?]
        at xyz.refinedev.core.acf.BukkitCommandManager.unregisterCommands(BukkitCommandManager.java:291) ~[?:?]
        at xyz.refinedev.core.acf.ACFBukkitListener.onPluginDisable(ACFBukkitListener.java:50) ~[?:?]
        at xyz.refinedev.core.acf.ACFBukkitListener$Access/2033809376.apply(Unknown Source) ~[?:?]
        at GandDanda1.kayaFurry0d(Unknown Source) ~[server.jar:?]
        at xyz.refinedev.spigot.utils.eventbusutil.methods.CallerImpl.call(CallerImpl.java) ~[server.jar:git-Carbon-0b81a54]
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$3(CarbonPluginLoader.java:167) ~[server.jar:git-Carbon-0b81a54]
        ... 11 more
```

**Comment by Komeek** [comment]
Fixed it. Issue was related to using the dependency system incorrectly.
