### ISSUE TITLE
ERROR: Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by FrahHS** [aikar/commands#408]
Sometimes i throw this error when a player join, i can't figure out why.

```
[19:19:04] [User Authenticator #2/INFO]: UUID of player Steve is 481df3d4-af5a-3e93-a140-988f1a17bc64
[19:19:05] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MyPlugin v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.a(PlayerList.java:294) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:129) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(SourceFile:20) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(SourceFile:7) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:33) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4039-Spigot-c198da2-4c687f2]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/acf/IssuerLocaleChangedCallback
	at com.acf.CommandManager.notifyLocaleChange(CommandManager.java:441) ~[?:?]
	at com.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:348) ~[?:?]
	at com.acf.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 21 more
[19:19:06] [Server thread/INFO]: Steve joined the game
[19:19:06] [Server thread/INFO]: Steve [/127.0.0.1:51407] logged in with entity id 1366 at ([world]10.357053984630312, 65.0, 50.37260426187748)
```

**Comment by FrahHS** [comment]
Notice:
`Caused by: java.lang.NoClassDefFoundError: com/acf/IssuerLocaleChangedCallback`
